### ISSUE TITLE
A JavaScript error occurred in the main process 

### ISSUE THREAD

**Issue by liupeidong0620** [asticode/go-astilectron#168]
```
[Window Title] Error [Main Instruction] A JavaScript error occurred in the main process [Content] Uncaught Exception: TypeError: Cannot read property 'show' of undefined at Interface.<anonymous> (C:\Users\Caleb\AppData\Roaming\Lets\vendor\astilectron\main.js:264:37)
 at Interface.emit (events.js:182:13)
 at Interface._onLine (readline.js:290:10) 
at Interface._normalWrite (readline.js:433:12) 
at Socket.ondata (readline.js:149:10) 
at Socket.emit (events.js:182:13) 
at addChunk (_stream_readable.js:283:12) 
at readableAddChunk (_stream_readable.js:264:11)
at Socket.Readable.push (_stream_readable.js:219:10) 
at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

- Machine: windows 10 

- create two windows with astilectron

This error occurs when closing the window. Is there any good solution for such an error?

**Comment by asticode** [comment]
How do you close the window? By clicking on the `close` button or programmatically?

Also, could you provide maybe some code sample so that I can reproduce easily?

**Comment by liupeidong0620** [comment]
Taskbar close. I passed the `window. Destroy ()`  close the window, no problem occurs.

Now there's too much code, I don't know if simple code can be reproduced.I'll try a simple example to see if it can be reproduced.

What's the way to block the ' taskbar close ' feature？

**Comment by asticode** [comment]
Can you try using `window.Close()` instead of `window.Destroy()`?

**Comment by liupeidong0620** [comment]
- [error example](https://github.com/liupeidong0620/go-astilectron-demo/tree/example)

- Machine: windows 10

- go-astilectron version 1.8.1

error info:
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at Interface.<anonymous> (C:\Users\Netpas\AppData\Roaming\Test\vendor\astilectron\main.js:249:36)
    at emitOne (events.js:115:13)
    at Interface.emit (events.js:210:7)
    at Interface._onLine (readline.js:278:10)
    at Interface._normalWrite (readline.js:420:12)
    at Socket.ondata (readline.js:138:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
```

**Comment by asticode** [comment]
You don't need to destroy the `Window` manually after the `Run` method.

**Comment by liupeidong0620** [comment]
Steps：

- go get github.com/liupeidong0620/go-astilectron-demo

- cd $GOPATH/src/github.com/liupeidong0620/go-astilectron-demo

- git checkout origin/example

- astilectron-bundler -v

Before you reproduce the error, you can try the following steps multiple times:

- run Test.exe

- click `Open the test window`

- click `Close the window`
