### ISSUE TITLE
Remove menu

### ISSUE THREAD

**Issue by zabuTNT** [asticode/go-astilectron#7]
Hi,
great job, but it seems that there is no way to remove the menu or simply set it to empty.
if I try with
`var m = a.NewMenu([]*astilectron.MenuItemOptions{})`
or
`var m = a.NewMenu(nil)`

I receive:
`Uncaught Exception:
TypeError: Cannot read property 'length' of undefined
    at menuCreate (/home/fede/goprojects/src/testElectron2/assets/vendor/astilectron/main.js:157:38)
    at Interface.<anonymous> (/home/fede/goprojects/src/testElectron2/assets/vendor/astilectron/main.js:42:39)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:247:10)
    at Interface.<anonymous> (readline.js:384:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:383:11)
    at Socket.ondata (readline.js:107:10)
    at emitOne (events.js:96:13)`

but I remember that in electron is possibile remove the Menu with something like that

`window.setMenu(null);`

It would be nice doing the same thing with this library too.
Or did I miss something?

Thank you in advance.

**Comment by asticode** [comment]
That's a great idea indeed, I'll add it this week-end.
I'll keep your posted.

**Comment by asticode** [comment]
All right so here's what I've added :

- Electron's default menus are removed
- you can now use `m.Destroy()` to remove a menu

If that meets your need, please close the issue.
Cheers

**Comment by asticode** [comment]
@zabuTNT did it fix your problem?

If so, could close this issue?

**Comment by zabuTNT** [comment]
Now I've an error when I get your package.

`# github.com/asticode/go-astilectron
../github.com/asticode/go-astilectron/paths.go:64: undefined: os.Executable`

**Comment by zabuTNT** [comment]
It works after fixed my issue with Executable() #9,

Thank you.
